@BASE_URL = http://localhost:5500/reportPost
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVhZDZiYTk4YTlkY2U2NjU0N2I2MjIiLCJpYXQiOjE2NDMxMTc1MDd9.QrpA5XH_R7gyBSbzlzvb2bJ8ImGc1oU6Oj9dktuMl70

@TOKEN1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmMwOGExNDFiMzNkNWM4OGY3YTIiLCJpYXQiOjE2NDMxMTc2NDl9.0NrcqSsChIHs2KoHDTAat937CrYbpdljc6ly4coVAug
@TOKEN2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmMxMGExNDFiMzNkNWM4OGY3YTUiLCJpYXQiOjE2NDMxMTc2NzF9.pCNomhk5K-Ez383UxMotNqSJYCUc_xvurjMrhhG3-Bg
@TOKEN3 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmMxOGExNDFiMzNkNWM4OGY3YTgiLCJpYXQiOjE2NDMxMTc2OTR9.FgZkvS9i8gPHL5mLWQOR44CxBN_kNu1dyvc4m6aMb7c
@TOKEN4 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmMxZmExNDFiMzNkNWM4OGY3YWIiLCJpYXQiOjE2NDMxMTc3MDh9.L3LK7xwrT-iXMRnt6wJ_nqpMC8DaXoKCLi2--RIJfWg
@TOKEN5 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmMyZGExNDFiMzNkNWM4OGY3YWUiLCJpYXQiOjE2NDMxMTc3MzB9.RlWmO3VrzQbd3O7ioiRdp6gcHbW0o8O2WVDRMFzHTrE
@TOKEN6 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmMzNmExNDFiMzNkNWM4OGY3YjEiLCJpYXQiOjE2NDMxMTc3NDJ9.kFyK8l4_2CSOlY78grd_JdldBA86IpTh4TLnNluNSLU
@TOKEN7 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmJmZmExNDFiMzNkNWM4OGY3OWYiLCJpYXQiOjE2NDMxMTc2MzN9.mr7r84zuSvtsTjD2P1RONIdo3fY6ZlOb8Ucq3GdDA14
@TOKEN8 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVmZmUzZWExNDFiMzNkNWM4OGY3ZGEiLCJpYXQiOjE2NDMxMTgxNTd9.hdm0yngF-V0USb9QkyNwykuZ2MCPfZkEmYawOp4WhSw


# Add Report 
POST {{BASE_URL}}/61ead57d98a9dce66547b3ab
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "report": "This is bad post"
}

###