@BASE_URL = http://localhost:5500/recipe
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWYxMWE3NmI4ZmRhZDAwMWI1NGRhZWYiLCJpYXQiOjE2NDMxOTEwMjZ9.Ns3X0tzfbnzN5PKxWrubomkmcxXT2Tpx0v1G8WYiFp0

# Add Recipe
POST {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Potata",
    "description": "Potato Chips",
}

###

# Add Recipe to Archive
POST {{BASE_URL}}/archive/61e6bfcfe5805b8728bb70da
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

    
# Get Archived Recipe
GET {{BASE_URL}}/archive
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

    # "preparation": 10,
    # "cooking": 20,
    # "ingredients": [{"quantity": 10, "unit": "tablespoon", "item": "Potato"},{"quantity": 10, "unit": "tablespoon", "item": "Potato"}],
    # "direction": ["WASH", "CUT", "COOK"]

###

# Delete Recipe
Delete {{BASE_URL}}/61f11ebee7eb24812b06b575
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

# Get recipe by id Recipe
GET {{BASE_URL}}/61f16582333566d837eac982
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
